# 테스트용으로만 처리. localhost 서버 정보만 기입할것.
server:
  port: 8018
spring:
  redis:
    host: localhost
    port: 6380
    password: 1234
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: elastic
      password: 1234
  datasource:
    hikari:
      maximum-pool-size: 2
    url: jdbc:mariadb://127.0.0.1:3306
    username: testuser
    password: testpass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none   # 필요에 따라 update/create 설정 가능
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true     # 콘솔에 SQL 출력
    format-sql: true

logging:
  level:
    root: info
    com.your.package: debug